[[libmplxx]]
arch = "x86_64"
git-tree-sha1 = "7744f0719758a79793187f8d0ec21133c3f3a882"
os = "macos"

    [[libmplxx.download]]
    sha256 = "56c10af8cddda0a2e09d8e1c968ae1a3d4e9cac9d38bb6acee82c31531822d31"
    url = "https://github.com/terasakisatoshi/MatplotWrapBuilder.jl/releases/download/v0.1.1/Binary.Packages.MacOSX.zip"
[[libmplxx]]
arch = "x86_64"
git-tree-sha1 = "75f221ceaad2f03f5851de233f3633b6eb10cbd2"
libc = "glibc"
os = "linux"

    [[libmplxx.download]]
    sha256 = "fbf3dab447ba7a2501dfca9e258d50ee5a9d3c8cc25a182fe4ab40186c3d4cca"
    url = "https://github.com/terasakisatoshi/MatplotWrapBuilder.jl/releases/download/v0.1.1/Binary.Packages.Linux.zip"
