[[libmplxx]]
arch = "x86_64"
git-tree-sha1 = "85442c45188f79d3e83a0c53ce9e1503df0f46a2"
os = "macos"

    [[libmplxx.download]]
    sha256 = "5cd9a4254001b25a841a4f8a06a5bc739030ad7daa65737994a7a4578051ea10"
    url = "https://github.com/terasakisatoshi/MatplotWrapBuilder.jl/releases/download/v0.2.0/Binary.Packages.MacOSX.tar.gz"
[[libmplxx]]
arch = "x86_64"
git-tree-sha1 = "e4c411290896e6276422d912a2a06130aed42628"
libc = "glibc"
os = "linux"

    [[libmplxx.download]]
    sha256 = "b16256fe3cede4cfe35635dda8475da63ad911d1170a50d5d3a2759d335dd450"
    url = "https://github.com/terasakisatoshi/MatplotWrapBuilder.jl/releases/download/v0.2.0/Binary.Packages.Linux.tar.gz"
